account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
  path('login/', views.LoginView.as_view(), name="login"),
  path('signup/', views.SignUpView.as_view(), name='signup'),
  path('logout/', views.logout_view, name='logout'),
  path(
      'users/',
      views.ListAccountView.as_view(),
      name='user_list'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/$',
      views.DetailAccountView.as_view(),
      name='profile'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/update/$',
      views.UpdateAccountView.as_view(),
      name='update'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/update/password/$',
      views.ChangePasswordView.as_view(),
      name='change_password'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/followers$',
      views.FollowersListView.as_view(),
      name='followers'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/following/$',
      views.FollowingListView.as_view(),
      name='following'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/follow/$',
      views.follow_view,
      name='follow'
  ),
  re_path(
      r'^(?P<username>[-\w]{5,30})/unfollow/$',
      views.unfollow_view,
      name='unfollow'
  ),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('posts/', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path, re_path
from . import views

app_name = 'post'

urlpatterns = [
  path(
        'create/',
        views.CreatePostView.as_view(),
        name='create'
    ),
  re_path(
      r'(?P<slug>[\w\-]{10})/$',
      views.DetailPostView.as_view(),
      name='view'
  ),
  re_path(
      r'(?P<slug>[\w\-]{10})/update/$',
      views.UpdatePostView.as_view(),
      name='update'
  ),
  re_path(
      r'(?P<slug>[\w\-]{10})/delete/$',
      views.DeletePostView.as_view(),
      name='delete'
  ),
  re_path(
      r'(?P<slug>[\w\-]{10})/like/$',
      views.like_post_view,
      name='like'
  ),
  re_path(
      r'(?P<slug>[\w\-]{10})/unlike/$',
      views.unlike_post_view,
      name='unlike'
  ),
]

templates/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    .messages {
        list-style: none;
    }
    .red, .red:hover, .red:visited,
    .red:active, .red:focus, .red:link {
        color: #d9534f;
    }
    .card-link {
      text-decoration: none;
      color: black;
    }
  </style>
  <script src="https://kit.fontawesome.com/aaeed7d0a3.js" crossorigin="anonymous"></script>
  <title>Instagram</title>
</head>
<body>
  {% include "navbar.html" %}

  {% block content %} {%endblock%}

  {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %}

    
    <script>
      var myModal = document.getElementById('myModal')
      var myInput = document.getElementById('myInput')

      myModal.addEventListener('shown.bs.modal', function () {
        myInput.focus()
      })
    </script>
  {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{{block.super}}

{% if user.is_authenticated %}
    {% for post in posts  %}
        <div class="container">
            <div class="col-3"></div>
            <div class="col-6">
                {% include 'posts/post.html' %}
            </div>
            <div class="col-3"></div>
        </div>
    {% endfor %}
{% else %}
    <p>Welcome to Instagram. Please log in.</p>
{% endif %}

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'home' %}">Instagram</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      </div>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link active" href="{{ user.get_absolute_url }}">{{ user.username }}</a>
          <a class="nav-item nav-link" href="{% url 'post:create' %}">Create Post</a>
          <a class="nav-item nav-link" href="{% url 'account:logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'account:login' %}">Login</a>
          <a class="nav-item nav-link" href="{% url 'account:signup' %}">Signup</a>
          {% endif %}
        </div>
      </div>
  </div>
</nav>